//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventureWorksLT2019.Resx.Resources {
    using System;

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UIStrings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIStrings() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdventureWorksLT2019.Resx.Resources.UIStrings", typeof(UIStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Advanced Search"".
        /// </summary>
        public static string AdvancedSearch {
            get {
                return ResourceManager.GetString("AdvancedSearch", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "عربي"".
        /// </summary>
        public static string Arabic {
            get {
                return ResourceManager.GetString("Arabic", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Are you sure you want to delete this?"".
        /// </summary>
        public static string Are_you_sure_you_want_to_delete_this_ {
            get {
                return ResourceManager.GetString("Are_you_sure_you_want_to_delete_this?", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Auto SignIn"".
        /// </summary>
        public static string AutoSignIn {
            get {
                return ResourceManager.GetString("AutoSignIn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Back to List"".
        /// </summary>
        public static string Back_to_List {
            get {
                return ResourceManager.GetString("Back_to_List", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Cancel"".
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "汉语"".
        /// </summary>
        public static string ChinesseSimplified {
            get {
                return ResourceManager.GetString("ChinesseSimplified", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Clear"".
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Confirm Password"".
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Passwords not match"".
        /// </summary>
        public static string ConfirmPasswordNotMatchError {
            get {
                return ResourceManager.GetString("ConfirmPasswordNotMatchError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Confirm Password Required"".
        /// </summary>
        public static string ConfirmPasswordRequired {
            get {
                return ResourceManager.GetString("ConfirmPasswordRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Contains"".
        /// </summary>
        public static string Contains {
            get {
                return ResourceManager.GetString("Contains", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Create"".
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Create New"".
        /// </summary>
        public static string Create_New {
            get {
                return ResourceManager.GetString("Create_New", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Create Another One"".
        /// </summary>
        public static string CreateAnotherOne {
            get {
                return ResourceManager.GetString("CreateAnotherOne", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Dark"".
        /// </summary>
        public static string Dark {
            get {
                return ResourceManager.GetString("Dark", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Dashboard"".
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Delete"".
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Deleted"".
        /// </summary>
        public static string Deleted {
            get {
                return ResourceManager.GetString("Deleted", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Deleting ..."".
        /// </summary>
        public static string Deleting {
            get {
                return ResourceManager.GetString("Deleting", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Deletion Failed."".
        /// </summary>
        public static string DeletionFailed {
            get {
                return ResourceManager.GetString("DeletionFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Details"".
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Done"".
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Edit"".
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Email"".
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Email Format Error"".
        /// </summary>
        public static string EmailFormatError {
            get {
                return ResourceManager.GetString("EmailFormatError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Email is Required"".
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Ends With"".
        /// </summary>
        public static string EndsWith {
            get {
                return ResourceManager.GetString("EndsWith", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "English"".
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Export to Csv"".
        /// </summary>
        public static string ExportToCsv {
            get {
                return ResourceManager.GetString("ExportToCsv", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Export to Excel"".
        /// </summary>
        public static string ExportToExcel {
            get {
                return ResourceManager.GetString("ExportToExcel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Failed To Save"".
        /// </summary>
        public static string FailedToSave {
            get {
                return ResourceManager.GetString("FailedToSave", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "First"".
        /// </summary>
        public static string First {
            get {
                return ResourceManager.GetString("First", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "First Time User"".
        /// </summary>
        public static string FirstTimeUser {
            get {
                return ResourceManager.GetString("FirstTimeUser", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "-- All {0} --"".
        /// </summary>
        public static string Format_All {
            get {
                return ResourceManager.GetString("Format_All", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "{0} Items Per Page"".
        /// </summary>
        public static string Format_ItemsPerPage {
            get {
                return ResourceManager.GetString("Format_ItemsPerPage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "-- Please Select {0} --"".
        /// </summary>
        public static string Format_Please_Select {
            get {
                return ResourceManager.GetString("Format_Please_Select", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Search text in {0} field"".
        /// </summary>
        public static string Format_SearchTextDescription {
            get {
                return ResourceManager.GetString("Format_SearchTextDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "français"".
        /// </summary>
        public static string French {
            get {
                return ResourceManager.GetString("French", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Hide Advanced Search"".
        /// </summary>
        public static string HideAdvancedSearch {
            get {
                return ResourceManager.GetString("HideAdvancedSearch", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Home"".
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Import"".
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Index"".
        /// </summary>
        public static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Language"".
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Last"".
        /// </summary>
        public static string Last {
            get {
                return ResourceManager.GetString("Last", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Light"".
        /// </summary>
        public static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "LogIn"".
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Log Out"".
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "More"".
        /// </summary>
        public static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "More Details"".
        /// </summary>
        public static string MoreDetails {
            get {
                return ResourceManager.GetString("MoreDetails", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Next"".
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Page Size"".
        /// </summary>
        public static string PageSize {
            get {
                return ResourceManager.GetString("PageSize", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Password"".
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Minimum eight characters, at least one uppercase letter, one lowercase letter, one number and one special character:"".
        /// </summary>
        public static string PasswordPatternError {
            get {
                return ResourceManager.GetString("PasswordPatternError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Password is Required"".
        /// </summary>
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Please confirm you going to move selected items to {0}"".
        /// </summary>
        public static string Please_confirm_you_going_to_set_selected_items_to {
            get {
                return ResourceManager.GetString("Please_confirm_you_going_to_set_selected_items_to", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Please confirm you want to delete selected {0}"".
        /// </summary>
        public static string Please_confirm_you_want_to_delete_selected {
            get {
                return ResourceManager.GetString("Please_confirm_you_want_to_delete_selected", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "All"".
        /// </summary>
        public static string PreDefinedDateTimeRanges_AllTime {
            get {
                return ResourceManager.GetString("PreDefinedDateTimeRanges_AllTime", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Custom"".
        /// </summary>
        public static string PreDefinedDateTimeRanges_Custom {
            get {
                return ResourceManager.GetString("PreDefinedDateTimeRanges_Custom", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Last Five Years"".
        /// </summary>
        public static string PreDefinedDateTimeRanges_LastFiveYears {
            get {
                return ResourceManager.GetString("PreDefinedDateTimeRanges_LastFiveYears", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Last Month"".
        /// </summary>
        public static string PreDefinedDateTimeRanges_LastMonth {
            get {
                return ResourceManager.GetString("PreDefinedDateTimeRanges_LastMonth", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Last Six Months"".
        /// </summary>
        public static string PreDefinedDateTimeRanges_LastSixMonths {
            get {
                return ResourceManager.GetString("PreDefinedDateTimeRanges_LastSixMonths", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Last Ten Years"".
        /// </summary>
        public static string PreDefinedDateTimeRanges_LastTenYears {
            get {
                return ResourceManager.GetString("PreDefinedDateTimeRanges_LastTenYears", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Last Three Months"".
        /// </summary>
        public static string PreDefinedDateTimeRanges_LastThreeMonths {
            get {
                return ResourceManager.GetString("PreDefinedDateTimeRanges_LastThreeMonths", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Last Week"".
        /// </summary>
        public static string PreDefinedDateTimeRanges_LastWeek {
            get {
                return ResourceManager.GetString("PreDefinedDateTimeRanges_LastWeek", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Last Year"".
        /// </summary>
        public static string PreDefinedDateTimeRanges_LastYear {
            get {
                return ResourceManager.GetString("PreDefinedDateTimeRanges_LastYear", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Next Five Years"".
        /// </summary>
        public static string PreDefinedDateTimeRanges_NextFiveYears {
            get {
                return ResourceManager.GetString("PreDefinedDateTimeRanges_NextFiveYears", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Next Month"".
        /// </summary>
        public static string PreDefinedDateTimeRanges_NextMonth {
            get {
                return ResourceManager.GetString("PreDefinedDateTimeRanges_NextMonth", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Next Six Months"".
        /// </summary>
        public static string PreDefinedDateTimeRanges_NextSixMonths {
            get {
                return ResourceManager.GetString("PreDefinedDateTimeRanges_NextSixMonths", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Next Ten Years"".
        /// </summary>
        public static string PreDefinedDateTimeRanges_NextTenYears {
            get {
                return ResourceManager.GetString("PreDefinedDateTimeRanges_NextTenYears", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Next Three Months"".
        /// </summary>
        public static string PreDefinedDateTimeRanges_NextThreeMonths {
            get {
                return ResourceManager.GetString("PreDefinedDateTimeRanges_NextThreeMonths", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Next Week"".
        /// </summary>
        public static string PreDefinedDateTimeRanges_NextWeek {
            get {
                return ResourceManager.GetString("PreDefinedDateTimeRanges_NextWeek", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Next Year"".
        /// </summary>
        public static string PreDefinedDateTimeRanges_NextYear {
            get {
                return ResourceManager.GetString("PreDefinedDateTimeRanges_NextYear", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "This Month"".
        /// </summary>
        public static string PreDefinedDateTimeRanges_ThisMonth {
            get {
                return ResourceManager.GetString("PreDefinedDateTimeRanges_ThisMonth", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "This Week"".
        /// </summary>
        public static string PreDefinedDateTimeRanges_ThisWeek {
            get {
                return ResourceManager.GetString("PreDefinedDateTimeRanges_ThisWeek", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "This Year"".
        /// </summary>
        public static string PreDefinedDateTimeRanges_ThisYear {
            get {
                return ResourceManager.GetString("PreDefinedDateTimeRanges_ThisYear", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Today"".
        /// </summary>
        public static string PreDefinedDateTimeRanges_Today {
            get {
                return ResourceManager.GetString("PreDefinedDateTimeRanges_Today", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Tomorrow"".
        /// </summary>
        public static string PreDefinedDateTimeRanges_Tomorrow {
            get {
                return ResourceManager.GetString("PreDefinedDateTimeRanges_Tomorrow", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Yesterday"".
        /// </summary>
        public static string PreDefinedDateTimeRanges_Yesterday {
            get {
                return ResourceManager.GetString("PreDefinedDateTimeRanges_Yesterday", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Previous"".
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Register"".
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Register A New User"".
        /// </summary>
        public static string RegisterANewUser {
            get {
                return ResourceManager.GetString("RegisterANewUser", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Remember Me"".
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Save"".
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Search text in all text fields"".
        /// </summary>
        public static string SearchTextDescription {
            get {
                return ResourceManager.GetString("SearchTextDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Select"".
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Settings"".
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Show Advanced Search"".
        /// </summary>
        public static string ShowAdvancedSearch {
            get {
                return ResourceManager.GetString("ShowAdvancedSearch", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Sort"".
        /// </summary>
        public static string Sort {
            get {
                return ResourceManager.GetString("Sort", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Española"".
        /// </summary>
        public static string Spanish {
            get {
                return ResourceManager.GetString("Spanish", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Starts With"".
        /// </summary>
        public static string StartsWith {
            get {
                return ResourceManager.GetString("StartsWith", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Successfully Saved"".
        /// </summary>
        public static string SuccessfullySaved {
            get {
                return ResourceManager.GetString("SuccessfullySaved", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Also a ..."".
        /// </summary>
        public static string Tab_AlsoA {
            get {
                return ResourceManager.GetString("Tab_AlsoA", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Theme"".
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Tile Size"".
        /// </summary>
        public static string TileSize {
            get {
                return ResourceManager.GetString("TileSize", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "System Information ID"".
        /// </summary>
        public static string SystemInformationID {
            get {
                return ResourceManager.GetString("SystemInformationID", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Database _ Version"".
        /// </summary>
        public static string Database_Version {
            get {
                return ResourceManager.GetString("Database_Version", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "The length of Database_Version should be 1 to 25"".
        /// </summary>
        public static string The_length_of_Database_Version_should_be_1_to_25 {
            get {
                return ResourceManager.GetString("The_length_of_Database_Version_should_be_1_to_25", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Version Date"".
        /// </summary>
        public static string VersionDate {
            get {
                return ResourceManager.GetString("VersionDate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "VersionDate is required"".
        /// </summary>
        public static string VersionDate_is_required {
            get {
                return ResourceManager.GetString("VersionDate_is_required", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Modified Date"".
        /// </summary>
        public static string ModifiedDate {
            get {
                return ResourceManager.GetString("ModifiedDate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "ModifiedDate is required"".
        /// </summary>
        public static string ModifiedDate_is_required {
            get {
                return ResourceManager.GetString("ModifiedDate_is_required", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Value"".
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Name"".
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Build Version"".
        /// </summary>
        public static string BuildVersion {
            get {
                return ResourceManager.GetString("BuildVersion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Error Log ID"".
        /// </summary>
        public static string ErrorLogID {
            get {
                return ResourceManager.GetString("ErrorLogID", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Error Time"".
        /// </summary>
        public static string ErrorTime {
            get {
                return ResourceManager.GetString("ErrorTime", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "ErrorTime is required"".
        /// </summary>
        public static string ErrorTime_is_required {
            get {
                return ResourceManager.GetString("ErrorTime_is_required", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "User Name"".
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "The length of UserName should be 1 to 128"".
        /// </summary>
        public static string The_length_of_UserName_should_be_1_to_128 {
            get {
                return ResourceManager.GetString("The_length_of_UserName_should_be_1_to_128", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Error Number"".
        /// </summary>
        public static string ErrorNumber {
            get {
                return ResourceManager.GetString("ErrorNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "ErrorNumber is required"".
        /// </summary>
        public static string ErrorNumber_is_required {
            get {
                return ResourceManager.GetString("ErrorNumber_is_required", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Error Severity"".
        /// </summary>
        public static string ErrorSeverity {
            get {
                return ResourceManager.GetString("ErrorSeverity", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Error State"".
        /// </summary>
        public static string ErrorState {
            get {
                return ResourceManager.GetString("ErrorState", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Error Procedure"".
        /// </summary>
        public static string ErrorProcedure {
            get {
                return ResourceManager.GetString("ErrorProcedure", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "The length of ErrorProcedure should be 0 to 126"".
        /// </summary>
        public static string The_length_of_ErrorProcedure_should_be_0_to_126 {
            get {
                return ResourceManager.GetString("The_length_of_ErrorProcedure_should_be_0_to_126", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Error Line"".
        /// </summary>
        public static string ErrorLine {
            get {
                return ResourceManager.GetString("ErrorLine", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Error Message"".
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "The length of ErrorMessage should be 1 to 4000"".
        /// </summary>
        public static string The_length_of_ErrorMessage_should_be_1_to_4000 {
            get {
                return ResourceManager.GetString("The_length_of_ErrorMessage_should_be_1_to_4000", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Error Log"".
        /// </summary>
        public static string ErrorLog {
            get {
                return ResourceManager.GetString("ErrorLog", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Address ID"".
        /// </summary>
        public static string AddressID {
            get {
                return ResourceManager.GetString("AddressID", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Address Line 1"".
        /// </summary>
        public static string AddressLine1 {
            get {
                return ResourceManager.GetString("AddressLine1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "The length of AddressLine1 should be 1 to 60"".
        /// </summary>
        public static string The_length_of_AddressLine1_should_be_1_to_60 {
            get {
                return ResourceManager.GetString("The_length_of_AddressLine1_should_be_1_to_60", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Address Line 2"".
        /// </summary>
        public static string AddressLine2 {
            get {
                return ResourceManager.GetString("AddressLine2", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "The length of AddressLine2 should be 0 to 60"".
        /// </summary>
        public static string The_length_of_AddressLine2_should_be_0_to_60 {
            get {
                return ResourceManager.GetString("The_length_of_AddressLine2_should_be_0_to_60", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "City"".
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "The length of City should be 1 to 30"".
        /// </summary>
        public static string The_length_of_City_should_be_1_to_30 {
            get {
                return ResourceManager.GetString("The_length_of_City_should_be_1_to_30", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "State Province"".
        /// </summary>
        public static string StateProvince {
            get {
                return ResourceManager.GetString("StateProvince", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "The length of StateProvince should be 1 to 50"".
        /// </summary>
        public static string The_length_of_StateProvince_should_be_1_to_50 {
            get {
                return ResourceManager.GetString("The_length_of_StateProvince_should_be_1_to_50", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Country Region"".
        /// </summary>
        public static string CountryRegion {
            get {
                return ResourceManager.GetString("CountryRegion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "The length of CountryRegion should be 1 to 50"".
        /// </summary>
        public static string The_length_of_CountryRegion_should_be_1_to_50 {
            get {
                return ResourceManager.GetString("The_length_of_CountryRegion_should_be_1_to_50", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Postal Code"".
        /// </summary>
        public static string PostalCode {
            get {
                return ResourceManager.GetString("PostalCode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "The length of PostalCode should be 1 to 15"".
        /// </summary>
        public static string The_length_of_PostalCode_should_be_1_to_15 {
            get {
                return ResourceManager.GetString("The_length_of_PostalCode_should_be_1_to_15", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "rowguid"".
        /// </summary>
        public static string rowguid {
            get {
                return ResourceManager.GetString("rowguid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "rowguid is required"".
        /// </summary>
        public static string rowguid_is_required {
            get {
                return ResourceManager.GetString("rowguid_is_required", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Address"".
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Lists"".
        /// </summary>
        public static string Tab_Lists {
            get {
                return ResourceManager.GetString("Tab_Lists", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Customer Addresses  Via  Address ID"".
        /// </summary>
        public static string Section_CustomerAddresses_Via_AddressID {
            get {
                return ResourceManager.GetString("Section_CustomerAddresses_Via_AddressID", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Sales Order Headers  Via  Bill To Address ID"".
        /// </summary>
        public static string Section_SalesOrderHeaders_Via_BillToAddressID {
            get {
                return ResourceManager.GetString("Section_SalesOrderHeaders_Via_BillToAddressID", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Sales Order Headers  Via  Ship To Address ID"".
        /// </summary>
        public static string Section_SalesOrderHeaders_Via_ShipToAddressID {
            get {
                return ResourceManager.GetString("Section_SalesOrderHeaders_Via_ShipToAddressID", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Customer ID"".
        /// </summary>
        public static string CustomerID {
            get {
                return ResourceManager.GetString("CustomerID", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Name Style"".
        /// </summary>
        public static string NameStyle {
            get {
                return ResourceManager.GetString("NameStyle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "NameStyle is required"".
        /// </summary>
        public static string NameStyle_is_required {
            get {
                return ResourceManager.GetString("NameStyle_is_required", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Title"".
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "The length of Title should be 0 to 8"".
        /// </summary>
        public static string The_length_of_Title_should_be_0_to_8 {
            get {
                return ResourceManager.GetString("The_length_of_Title_should_be_0_to_8", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "First Name"".
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "The length of FirstName should be 1 to 50"".
        /// </summary>
        public static string The_length_of_FirstName_should_be_1_to_50 {
            get {
                return ResourceManager.GetString("The_length_of_FirstName_should_be_1_to_50", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Middle Name"".
        /// </summary>
        public static string MiddleName {
            get {
                return ResourceManager.GetString("MiddleName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "The length of MiddleName should be 0 to 50"".
        /// </summary>
        public static string The_length_of_MiddleName_should_be_0_to_50 {
            get {
                return ResourceManager.GetString("The_length_of_MiddleName_should_be_0_to_50", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Last Name"".
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "The length of LastName should be 1 to 50"".
        /// </summary>
        public static string The_length_of_LastName_should_be_1_to_50 {
            get {
                return ResourceManager.GetString("The_length_of_LastName_should_be_1_to_50", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Suffix"".
        /// </summary>
        public static string Suffix {
            get {
                return ResourceManager.GetString("Suffix", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "The length of Suffix should be 0 to 10"".
        /// </summary>
        public static string The_length_of_Suffix_should_be_0_to_10 {
            get {
                return ResourceManager.GetString("The_length_of_Suffix_should_be_0_to_10", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Company Name"".
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "The length of CompanyName should be 0 to 128"".
        /// </summary>
        public static string The_length_of_CompanyName_should_be_0_to_128 {
            get {
                return ResourceManager.GetString("The_length_of_CompanyName_should_be_0_to_128", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Sales Person"".
        /// </summary>
        public static string SalesPerson {
            get {
                return ResourceManager.GetString("SalesPerson", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "The length of SalesPerson should be 0 to 256"".
        /// </summary>
        public static string The_length_of_SalesPerson_should_be_0_to_256 {
            get {
                return ResourceManager.GetString("The_length_of_SalesPerson_should_be_0_to_256", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Email Address"".
        /// </summary>
        public static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "The length of EmailAddress should be 0 to 50"".
        /// </summary>
        public static string The_length_of_EmailAddress_should_be_0_to_50 {
            get {
                return ResourceManager.GetString("The_length_of_EmailAddress_should_be_0_to_50", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Phone"".
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "The length of Phone should be 0 to 25"".
        /// </summary>
        public static string The_length_of_Phone_should_be_0_to_25 {
            get {
                return ResourceManager.GetString("The_length_of_Phone_should_be_0_to_25", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Password Hash"".
        /// </summary>
        public static string PasswordHash {
            get {
                return ResourceManager.GetString("PasswordHash", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "The length of PasswordHash should be 1 to 128"".
        /// </summary>
        public static string The_length_of_PasswordHash_should_be_1_to_128 {
            get {
                return ResourceManager.GetString("The_length_of_PasswordHash_should_be_1_to_128", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Password Salt"".
        /// </summary>
        public static string PasswordSalt {
            get {
                return ResourceManager.GetString("PasswordSalt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "The length of PasswordSalt should be 1 to 10"".
        /// </summary>
        public static string The_length_of_PasswordSalt_should_be_1_to_10 {
            get {
                return ResourceManager.GetString("The_length_of_PasswordSalt_should_be_1_to_10", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Customer"".
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Customer Addresses  Via  Customer ID"".
        /// </summary>
        public static string Section_CustomerAddresses_Via_CustomerID {
            get {
                return ResourceManager.GetString("Section_CustomerAddresses_Via_CustomerID", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Sales Order Headers  Via  Customer ID"".
        /// </summary>
        public static string Section_SalesOrderHeaders_Via_CustomerID {
            get {
                return ResourceManager.GetString("Section_SalesOrderHeaders_Via_CustomerID", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "CustomerID is required"".
        /// </summary>
        public static string CustomerID_is_required {
            get {
                return ResourceManager.GetString("CustomerID_is_required", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "AddressID is required"".
        /// </summary>
        public static string AddressID_is_required {
            get {
                return ResourceManager.GetString("AddressID_is_required", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Address Type"".
        /// </summary>
        public static string AddressType {
            get {
                return ResourceManager.GetString("AddressType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "The length of AddressType should be 1 to 50"".
        /// </summary>
        public static string The_length_of_AddressType_should_be_1_to_50 {
            get {
                return ResourceManager.GetString("The_length_of_AddressType_should_be_1_to_50", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Customer Address"".
        /// </summary>
        public static string CustomerAddress {
            get {
                return ResourceManager.GetString("CustomerAddress", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Product ID"".
        /// </summary>
        public static string ProductID {
            get {
                return ResourceManager.GetString("ProductID", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "The length of Name should be 1 to 50"".
        /// </summary>
        public static string The_length_of_Name_should_be_1_to_50 {
            get {
                return ResourceManager.GetString("The_length_of_Name_should_be_1_to_50", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Product Number"".
        /// </summary>
        public static string ProductNumber {
            get {
                return ResourceManager.GetString("ProductNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "The length of ProductNumber should be 1 to 25"".
        /// </summary>
        public static string The_length_of_ProductNumber_should_be_1_to_25 {
            get {
                return ResourceManager.GetString("The_length_of_ProductNumber_should_be_1_to_25", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Color"".
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "The length of Color should be 0 to 15"".
        /// </summary>
        public static string The_length_of_Color_should_be_0_to_15 {
            get {
                return ResourceManager.GetString("The_length_of_Color_should_be_0_to_15", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Standard Cost"".
        /// </summary>
        public static string StandardCost {
            get {
                return ResourceManager.GetString("StandardCost", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "StandardCost is required"".
        /// </summary>
        public static string StandardCost_is_required {
            get {
                return ResourceManager.GetString("StandardCost_is_required", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "List Price"".
        /// </summary>
        public static string ListPrice {
            get {
                return ResourceManager.GetString("ListPrice", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "ListPrice is required"".
        /// </summary>
        public static string ListPrice_is_required {
            get {
                return ResourceManager.GetString("ListPrice_is_required", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Size"".
        /// </summary>
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "The length of Size should be 0 to 5"".
        /// </summary>
        public static string The_length_of_Size_should_be_0_to_5 {
            get {
                return ResourceManager.GetString("The_length_of_Size_should_be_0_to_5", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Weight"".
        /// </summary>
        public static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Product Category"".
        /// </summary>
        public static string ProductCategoryID {
            get {
                return ResourceManager.GetString("ProductCategoryID", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Product Model"".
        /// </summary>
        public static string ProductModelID {
            get {
                return ResourceManager.GetString("ProductModelID", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Sell Start Date"".
        /// </summary>
        public static string SellStartDate {
            get {
                return ResourceManager.GetString("SellStartDate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "SellStartDate is required"".
        /// </summary>
        public static string SellStartDate_is_required {
            get {
                return ResourceManager.GetString("SellStartDate_is_required", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Sell End Date"".
        /// </summary>
        public static string SellEndDate {
            get {
                return ResourceManager.GetString("SellEndDate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Discontinued Date"".
        /// </summary>
        public static string DiscontinuedDate {
            get {
                return ResourceManager.GetString("DiscontinuedDate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Thumb Nail Photo"".
        /// </summary>
        public static string ThumbNailPhoto {
            get {
                return ResourceManager.GetString("ThumbNailPhoto", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Thumbnail Photo File Name"".
        /// </summary>
        public static string ThumbnailPhotoFileName {
            get {
                return ResourceManager.GetString("ThumbnailPhotoFileName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "The length of ThumbnailPhotoFileName should be 0 to 50"".
        /// </summary>
        public static string The_length_of_ThumbnailPhotoFileName_should_be_0_to_50 {
            get {
                return ResourceManager.GetString("The_length_of_ThumbnailPhotoFileName_should_be_0_to_50", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Product Category"".
        /// </summary>
        public static string ProductCategory {
            get {
                return ResourceManager.GetString("ProductCategory", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Product Model"".
        /// </summary>
        public static string ProductModel {
            get {
                return ResourceManager.GetString("ProductModel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Product Category"".
        /// </summary>
        public static string Parent {
            get {
                return ResourceManager.GetString("Parent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Product"".
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Sales Order Details  Via  Product ID"".
        /// </summary>
        public static string Section_SalesOrderDetails_Via_ProductID {
            get {
                return ResourceManager.GetString("Section_SalesOrderDetails_Via_ProductID", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Product Category"".
        /// </summary>
        public static string ParentProductCategoryID {
            get {
                return ResourceManager.GetString("ParentProductCategoryID", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Recursive Path __"".
        /// </summary>
        public static string RecursivePath__ {
            get {
                return ResourceManager.GetString("RecursivePath__", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Products  Via  Product Category ID"".
        /// </summary>
        public static string Section_Products_Via_ProductCategoryID {
            get {
                return ResourceManager.GetString("Section_Products_Via_ProductCategoryID", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Product Categories  Via  Parent Product Category ID"".
        /// </summary>
        public static string Section_ProductCategories_Via_ParentProductCategoryID {
            get {
                return ResourceManager.GetString("Section_ProductCategories_Via_ParentProductCategoryID", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Product Description ID"".
        /// </summary>
        public static string ProductDescriptionID {
            get {
                return ResourceManager.GetString("ProductDescriptionID", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Description"".
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "The length of Description should be 1 to 400"".
        /// </summary>
        public static string The_length_of_Description_should_be_1_to_400 {
            get {
                return ResourceManager.GetString("The_length_of_Description_should_be_1_to_400", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Product Description"".
        /// </summary>
        public static string ProductDescription {
            get {
                return ResourceManager.GetString("ProductDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Product Model Product Descriptions  Via  Product Description ID"".
        /// </summary>
        public static string Section_ProductModelProductDescriptions_Via_ProductDescriptionID {
            get {
                return ResourceManager.GetString("Section_ProductModelProductDescriptions_Via_ProductDescriptionID", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Catalog Description"".
        /// </summary>
        public static string CatalogDescription {
            get {
                return ResourceManager.GetString("CatalogDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Products  Via  Product Model ID"".
        /// </summary>
        public static string Section_Products_Via_ProductModelID {
            get {
                return ResourceManager.GetString("Section_Products_Via_ProductModelID", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Product Model Product Descriptions  Via  Product Model ID"".
        /// </summary>
        public static string Section_ProductModelProductDescriptions_Via_ProductModelID {
            get {
                return ResourceManager.GetString("Section_ProductModelProductDescriptions_Via_ProductModelID", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "ProductModelID is required"".
        /// </summary>
        public static string ProductModelID_is_required {
            get {
                return ResourceManager.GetString("ProductModelID_is_required", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "ProductDescriptionID is required"".
        /// </summary>
        public static string ProductDescriptionID_is_required {
            get {
                return ResourceManager.GetString("ProductDescriptionID_is_required", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Culture"".
        /// </summary>
        public static string Culture_ {
            get {
                return ResourceManager.GetString("Culture_", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "The length of Culture should be 1 to 6"".
        /// </summary>
        public static string The_length_of_Culture_should_be_1_to_6 {
            get {
                return ResourceManager.GetString("The_length_of_Culture_should_be_1_to_6", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Product Model Product Description"".
        /// </summary>
        public static string ProductModelProductDescription {
            get {
                return ResourceManager.GetString("ProductModelProductDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Sales Order Header"".
        /// </summary>
        public static string SalesOrderID {
            get {
                return ResourceManager.GetString("SalesOrderID", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "SalesOrderID is required"".
        /// </summary>
        public static string SalesOrderID_is_required {
            get {
                return ResourceManager.GetString("SalesOrderID_is_required", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Sales Order Detail ID"".
        /// </summary>
        public static string SalesOrderDetailID {
            get {
                return ResourceManager.GetString("SalesOrderDetailID", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Order Qty"".
        /// </summary>
        public static string OrderQty {
            get {
                return ResourceManager.GetString("OrderQty", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "OrderQty is required"".
        /// </summary>
        public static string OrderQty_is_required {
            get {
                return ResourceManager.GetString("OrderQty_is_required", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "ProductID is required"".
        /// </summary>
        public static string ProductID_is_required {
            get {
                return ResourceManager.GetString("ProductID_is_required", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Unit Price"".
        /// </summary>
        public static string UnitPrice {
            get {
                return ResourceManager.GetString("UnitPrice", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "UnitPrice is required"".
        /// </summary>
        public static string UnitPrice_is_required {
            get {
                return ResourceManager.GetString("UnitPrice_is_required", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Unit Price Discount"".
        /// </summary>
        public static string UnitPriceDiscount {
            get {
                return ResourceManager.GetString("UnitPriceDiscount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "UnitPriceDiscount is required"".
        /// </summary>
        public static string UnitPriceDiscount_is_required {
            get {
                return ResourceManager.GetString("UnitPriceDiscount_is_required", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Line Total"".
        /// </summary>
        public static string LineTotal {
            get {
                return ResourceManager.GetString("LineTotal", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Sales Order Header"".
        /// </summary>
        public static string SalesOrderHeader {
            get {
                return ResourceManager.GetString("SalesOrderHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Sales Order Number"".
        /// </summary>
        public static string SalesOrderNumber {
            get {
                return ResourceManager.GetString("SalesOrderNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Product Category"".
        /// </summary>
        public static string ProductCategory_Parent {
            get {
                return ResourceManager.GetString("ProductCategory_Parent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Address"".
        /// </summary>
        public static string BillTo {
            get {
                return ResourceManager.GetString("BillTo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Address"".
        /// </summary>
        public static string ShipTo {
            get {
                return ResourceManager.GetString("ShipTo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Sales Order Detail"".
        /// </summary>
        public static string SalesOrderDetail {
            get {
                return ResourceManager.GetString("SalesOrderDetail", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "More Details"".
        /// </summary>
        public static string Tab_MoreDetails {
            get {
                return ResourceManager.GetString("Tab_MoreDetails", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Product"".
        /// </summary>
        public static string Section_Product {
            get {
                return ResourceManager.GetString("Section_Product", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Sales Order Header"".
        /// </summary>
        public static string Section_SalesOrderHeader {
            get {
                return ResourceManager.GetString("Section_SalesOrderHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Revision Number"".
        /// </summary>
        public static string RevisionNumber {
            get {
                return ResourceManager.GetString("RevisionNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "RevisionNumber is required"".
        /// </summary>
        public static string RevisionNumber_is_required {
            get {
                return ResourceManager.GetString("RevisionNumber_is_required", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Order Date"".
        /// </summary>
        public static string OrderDate {
            get {
                return ResourceManager.GetString("OrderDate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "OrderDate is required"".
        /// </summary>
        public static string OrderDate_is_required {
            get {
                return ResourceManager.GetString("OrderDate_is_required", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Due Date"".
        /// </summary>
        public static string DueDate {
            get {
                return ResourceManager.GetString("DueDate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "DueDate is required"".
        /// </summary>
        public static string DueDate_is_required {
            get {
                return ResourceManager.GetString("DueDate_is_required", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Ship Date"".
        /// </summary>
        public static string ShipDate {
            get {
                return ResourceManager.GetString("ShipDate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Status"".
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Status is required"".
        /// </summary>
        public static string Status_is_required {
            get {
                return ResourceManager.GetString("Status_is_required", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Online Order Flag"".
        /// </summary>
        public static string OnlineOrderFlag {
            get {
                return ResourceManager.GetString("OnlineOrderFlag", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "OnlineOrderFlag is required"".
        /// </summary>
        public static string OnlineOrderFlag_is_required {
            get {
                return ResourceManager.GetString("OnlineOrderFlag_is_required", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "The length of SalesOrderNumber should be 0 to 25"".
        /// </summary>
        public static string The_length_of_SalesOrderNumber_should_be_0_to_25 {
            get {
                return ResourceManager.GetString("The_length_of_SalesOrderNumber_should_be_0_to_25", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Purchase Order Number"".
        /// </summary>
        public static string PurchaseOrderNumber {
            get {
                return ResourceManager.GetString("PurchaseOrderNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "The length of PurchaseOrderNumber should be 0 to 25"".
        /// </summary>
        public static string The_length_of_PurchaseOrderNumber_should_be_0_to_25 {
            get {
                return ResourceManager.GetString("The_length_of_PurchaseOrderNumber_should_be_0_to_25", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Account Number"".
        /// </summary>
        public static string AccountNumber {
            get {
                return ResourceManager.GetString("AccountNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "The length of AccountNumber should be 0 to 15"".
        /// </summary>
        public static string The_length_of_AccountNumber_should_be_0_to_15 {
            get {
                return ResourceManager.GetString("The_length_of_AccountNumber_should_be_0_to_15", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Address"".
        /// </summary>
        public static string ShipToAddressID {
            get {
                return ResourceManager.GetString("ShipToAddressID", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Address"".
        /// </summary>
        public static string BillToAddressID {
            get {
                return ResourceManager.GetString("BillToAddressID", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Ship Method"".
        /// </summary>
        public static string ShipMethod {
            get {
                return ResourceManager.GetString("ShipMethod", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "The length of ShipMethod should be 1 to 50"".
        /// </summary>
        public static string The_length_of_ShipMethod_should_be_1_to_50 {
            get {
                return ResourceManager.GetString("The_length_of_ShipMethod_should_be_1_to_50", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Credit Card Approval Code"".
        /// </summary>
        public static string CreditCardApprovalCode {
            get {
                return ResourceManager.GetString("CreditCardApprovalCode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "The length of CreditCardApprovalCode should be 0 to 15"".
        /// </summary>
        public static string The_length_of_CreditCardApprovalCode_should_be_0_to_15 {
            get {
                return ResourceManager.GetString("The_length_of_CreditCardApprovalCode_should_be_0_to_15", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Sub Total"".
        /// </summary>
        public static string SubTotal {
            get {
                return ResourceManager.GetString("SubTotal", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "SubTotal is required"".
        /// </summary>
        public static string SubTotal_is_required {
            get {
                return ResourceManager.GetString("SubTotal_is_required", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Tax Amt"".
        /// </summary>
        public static string TaxAmt {
            get {
                return ResourceManager.GetString("TaxAmt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "TaxAmt is required"".
        /// </summary>
        public static string TaxAmt_is_required {
            get {
                return ResourceManager.GetString("TaxAmt_is_required", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Freight"".
        /// </summary>
        public static string Freight {
            get {
                return ResourceManager.GetString("Freight", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Freight is required"".
        /// </summary>
        public static string Freight_is_required {
            get {
                return ResourceManager.GetString("Freight_is_required", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Total Due"".
        /// </summary>
        public static string TotalDue {
            get {
                return ResourceManager.GetString("TotalDue", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Comment"".
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "The length of Comment should be 0 to MAX"".
        /// </summary>
        public static string The_length_of_Comment_should_be_0_to_MAX {
            get {
                return ResourceManager.GetString("The_length_of_Comment_should_be_0_to_MAX", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Sales Order Details  Via  Sales Order ID"".
        /// </summary>
        public static string Section_SalesOrderDetails_Via_SalesOrderID {
            get {
                return ResourceManager.GetString("Section_SalesOrderDetails_Via_SalesOrderID", resourceCulture);
            }
        }

    }
}

