<Project Sdk="Microsoft.NET.Sdk.Web" >

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>2b286daa-7a92-44e7-b54b-72c8edb8a79d</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
<ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer.NetTopologySuite" Version="8.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
</ItemGroup>
<ItemGroup>
    <ProjectReference Include="..\EFCoreContext\AdventureWorksLT2019.EFCoreContext.csproj" />
    <ProjectReference Include="..\EFCoreRepositories\AdventureWorksLT2019.EFCoreRepositories.csproj" />
    <ProjectReference Include="..\..\Shared\Framework\Framework.csproj" />
    <ProjectReference Include="..\..\Shared\Framework.Mvc\Framework.Mvc.csproj" />
    <ProjectReference Include="..\Models\AdventureWorksLT2019.Models.csproj" />
    <ProjectReference Include="..\RepositoryContracts\AdventureWorksLT2019.RepositoryContracts.csproj" />
    <ProjectReference Include="..\Resx\AdventureWorksLT2019.Resx.csproj" />
    <ProjectReference Include="..\ServiceContracts\AdventureWorksLT2019.ServiceContracts.csproj" />
    <ProjectReference Include="..\Services\AdventureWorksLT2019.Services.csproj" />
    <ProjectReference Include="..\WebApiClientControllers\AdventureWorksLT2019.WebApiClientControllers.csproj" />
</ItemGroup>

</Project>
