<Project Sdk="Microsoft.NET.Sdk" >

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
<ItemGroup>
    <PackageReference Include="CSharpVitamins.ShortGuid" Version="2.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.DynamicLinq" Version="8.3.7" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer.NetTopologySuite" Version="8.0.0" />
    <PackageReference Include="ProjNet" Version="2.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
    <PackageReference Include="Z.EntityFramework.Extensions.EFCore" Version="8.101.1.3" />
</ItemGroup>
<ItemGroup>
    <ProjectReference Include="..\EFCoreContext\AdventureWorksLT2019.EFCoreContext.csproj" />
    <ProjectReference Include="..\..\Shared\Framework\Framework.csproj" />
    <ProjectReference Include="..\..\Shared\Framework.Mvc\Framework.Mvc.csproj" />
    <ProjectReference Include="..\Models\AdventureWorksLT2019.Models.csproj" />
    <ProjectReference Include="..\RepositoryContracts\AdventureWorksLT2019.RepositoryContracts.csproj" />
</ItemGroup>

</Project>
