//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Framework.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GlobalUIStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalUIStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Framework.Common.Resources.GlobalUIStrings", typeof(GlobalUIStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Search.
        /// </summary>
        internal static string AdvancedSearch {
            get {
                return ResourceManager.GetString("AdvancedSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this?.
        /// </summary>
        internal static string Are_you_sure_you_want_to_delete_this_ {
            get {
                return ResourceManager.GetString("Are you sure you want to delete this?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to List.
        /// </summary>
        internal static string Back_to_List {
            get {
                return ResourceManager.GetString("Back to List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains.
        /// </summary>
        internal static string Contains {
            get {
                return ResourceManager.GetString("Contains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New.
        /// </summary>
        internal static string Create_New {
            get {
                return ResourceManager.GetString("Create New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ends With.
        /// </summary>
        internal static string EndsWith {
            get {
                return ResourceManager.GetString("EndsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to Csv.
        /// </summary>
        internal static string ExportToCsv {
            get {
                return ResourceManager.GetString("ExportToCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to Excel.
        /// </summary>
        internal static string ExportToExcel {
            get {
                return ResourceManager.GetString("ExportToExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First.
        /// </summary>
        internal static string First {
            get {
                return ResourceManager.GetString("First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- All {0} --.
        /// </summary>
        internal static string Format_All {
            get {
                return ResourceManager.GetString("Format_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Items Per Page.
        /// </summary>
        internal static string Format_ItemsPerPage {
            get {
                return ResourceManager.GetString("Format_ItemsPerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Please Select {0} --.
        /// </summary>
        internal static string Format_Please_Select {
            get {
                return ResourceManager.GetString("Format_Please_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search text in {0} field.
        /// </summary>
        internal static string Format_SearchTextDescription {
            get {
                return ResourceManager.GetString("Format_SearchTextDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Advanced Search.
        /// </summary>
        internal static string HideAdvancedSearch {
            get {
                return ResourceManager.GetString("HideAdvancedSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        internal static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        internal static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        internal static string Last {
            get {
                return ResourceManager.GetString("Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        internal static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Details.
        /// </summary>
        internal static string MoreDetails {
            get {
                return ResourceManager.GetString("MoreDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm you going to move selected items to {0}.
        /// </summary>
        internal static string Please_confirm_you_going_to_set_selected_items_to {
            get {
                return ResourceManager.GetString("Please confirm you going to set selected items to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm you want to delete selected {0}.
        /// </summary>
        internal static string Please_confirm_you_want_to_delete_selected {
            get {
                return ResourceManager.GetString("Please confirm you want to delete selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        internal static string PreDefinedDateTimeRanges_Custom {
            get {
                return ResourceManager.GetString("PreDefinedDateTimeRanges_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Five Years.
        /// </summary>
        internal static string PreDefinedDateTimeRanges_LastFiveYears {
            get {
                return ResourceManager.GetString("PreDefinedDateTimeRanges_LastFiveYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Month.
        /// </summary>
        internal static string PreDefinedDateTimeRanges_LastMonth {
            get {
                return ResourceManager.GetString("PreDefinedDateTimeRanges_LastMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Six Months.
        /// </summary>
        internal static string PreDefinedDateTimeRanges_LastSixMonths {
            get {
                return ResourceManager.GetString("PreDefinedDateTimeRanges_LastSixMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Ten Years.
        /// </summary>
        internal static string PreDefinedDateTimeRanges_LastTenYears {
            get {
                return ResourceManager.GetString("PreDefinedDateTimeRanges_LastTenYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Three Months.
        /// </summary>
        internal static string PreDefinedDateTimeRanges_LastThreeMonths {
            get {
                return ResourceManager.GetString("PreDefinedDateTimeRanges_LastThreeMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Week.
        /// </summary>
        internal static string PreDefinedDateTimeRanges_LastWeek {
            get {
                return ResourceManager.GetString("PreDefinedDateTimeRanges_LastWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Year.
        /// </summary>
        internal static string PreDefinedDateTimeRanges_LastYear {
            get {
                return ResourceManager.GetString("PreDefinedDateTimeRanges_LastYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Five Years.
        /// </summary>
        internal static string PreDefinedDateTimeRanges_NextFiveYears {
            get {
                return ResourceManager.GetString("PreDefinedDateTimeRanges_NextFiveYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Month.
        /// </summary>
        internal static string PreDefinedDateTimeRanges_NextMonth {
            get {
                return ResourceManager.GetString("PreDefinedDateTimeRanges_NextMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Six Months.
        /// </summary>
        internal static string PreDefinedDateTimeRanges_NextSixMonths {
            get {
                return ResourceManager.GetString("PreDefinedDateTimeRanges_NextSixMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Ten Years.
        /// </summary>
        internal static string PreDefinedDateTimeRanges_NextTenYears {
            get {
                return ResourceManager.GetString("PreDefinedDateTimeRanges_NextTenYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Three Months.
        /// </summary>
        internal static string PreDefinedDateTimeRanges_NextThreeMonths {
            get {
                return ResourceManager.GetString("PreDefinedDateTimeRanges_NextThreeMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Week.
        /// </summary>
        internal static string PreDefinedDateTimeRanges_NextWeek {
            get {
                return ResourceManager.GetString("PreDefinedDateTimeRanges_NextWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Year.
        /// </summary>
        internal static string PreDefinedDateTimeRanges_NextYear {
            get {
                return ResourceManager.GetString("PreDefinedDateTimeRanges_NextYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Month.
        /// </summary>
        internal static string PreDefinedDateTimeRanges_ThisMonth {
            get {
                return ResourceManager.GetString("PreDefinedDateTimeRanges_ThisMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Week.
        /// </summary>
        internal static string PreDefinedDateTimeRanges_ThisWeek {
            get {
                return ResourceManager.GetString("PreDefinedDateTimeRanges_ThisWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Year.
        /// </summary>
        internal static string PreDefinedDateTimeRanges_ThisYear {
            get {
                return ResourceManager.GetString("PreDefinedDateTimeRanges_ThisYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        internal static string PreDefinedDateTimeRanges_Today {
            get {
                return ResourceManager.GetString("PreDefinedDateTimeRanges_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tomorrow.
        /// </summary>
        internal static string PreDefinedDateTimeRanges_Tomorrow {
            get {
                return ResourceManager.GetString("PreDefinedDateTimeRanges_Tomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yesterday.
        /// </summary>
        internal static string PreDefinedDateTimeRanges_Yesterday {
            get {
                return ResourceManager.GetString("PreDefinedDateTimeRanges_Yesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        internal static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search text in all text fields.
        /// </summary>
        internal static string SearchTextDescription {
            get {
                return ResourceManager.GetString("SearchTextDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Advanced Search.
        /// </summary>
        internal static string ShowAdvancedSearch {
            get {
                return ResourceManager.GetString("ShowAdvancedSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts With.
        /// </summary>
        internal static string StartsWith {
            get {
                return ResourceManager.GetString("StartsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Also a ....
        /// </summary>
        internal static string Tab_AlsoA {
            get {
                return ResourceManager.GetString("Tab_AlsoA", resourceCulture);
            }
        }
    }
}
